version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:    ${PGUSER:-appuser}
      POSTGRES_PASSWORD: ${PGPASSWORD:-apppassword}
      POSTGRES_DB:      ${PGDATABASE:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  notifier:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["node", "dist/cron/emailReminderJob.js"]
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: .              
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://api:4000
    depends_on:
      - api

volumes:
  db-data:
